name: Playwright Tests + Allure Report
on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - name: Install Playwright browsers
        run: playwright install --with-deps chromium

      - name: Run tests
        env:
          LOGIN_PAGE_URL: ${{ secrets.LOGIN_PAGE_URL }}
          REGISTRATION_PAGE_URL: ${{ secrets.REGISTRATION_PAGE_URL }}
          FORGOT_PASSWORD_PAGE: ${{ secrets.FORGOT_PASSWORD_PAGE }}
          FORM_SUBMISSION_PAGE: ${{secrets.FORGOT_PASSWORD_PAGE }}
          DRAG_AND_DROP_PAGE: ${{secrets.DRAG_AND_DROP_PAGE }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: pytest --alluredir=allure-results
        continue-on-error: true

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 30

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        if: always()
        with:
          path: allure-history

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        if: always()
